### ISSUE TITLE
PSXperia tool "Convert" button problem

### ISSUE THREAD

**Issue by Sqwurtski** [yifanlu/PSXperia#60]
Alright, i've been at this for a while. Step by step from scratch many times. Its sort of making me mad. Everytime i try to convert my Iso file using the tool, nothing happens. I click and it still says "checking to make sure all files are there".

So I used another game thats more common, Crash 3, it is in .iso format and it still stays  the same. Grr lol

**Comment by tisaoil** [comment]
I'm having this trouble to...
Done every thing right.. Re-read and re-done everything again.. And allways same result [checking(...)]

What can I do..?

**Comment by tisaoil** [comment]
So this is my log file:

[I] Starting extraction with PSXPeria Extractor version 2.0 Beta
[I] Verifying files
[I] Identified Crash Bandicoot EUR Version 1.0.3, CRC32: 7C33475B
[I] Decoding values
[I] Extracting APK
[I] Extracting ZIP file: C:\Users\Sal\Desktop\psx\On Xplay\com.sony.playstation.ncea00344_1.apk to: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data
[D] Done extracting ZIP.
[I] Extracting ZPAKS
[I] Extracting ZIP file: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\assets\NCEA00344_1_2.zpak to: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\assets\ZPAK
[D] Done extracting ZIP.
[I] Extracting ZIP file: C:\Users\Sal\Desktop\psx\On Xplay\assets\NCEA00344_1_2.zpak to: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\ZPAK
[D] Done extracting ZIP.
[I] Removing unneeded files.
[I] Adding new files.
[I] Patching XML strings with tags.
[D] Replacing strings in XML data.
[D] Writing to temporary file: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\assets\AndroidManifest.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\assets\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\res\values\strings.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\data\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Done with string replacement.
[I] Verifying the emulator binary.
[I] Patching emulator.
[I] Done.
[I] PSXperiaTool initialized, outputting to: C:\Users\Sal\Desktop\psx\psxperia-2.0-beta (2).\output
[I] Starting build with PSXPeria Converter version 2.0 Beta
[I] Checking to make sure all files are there.

Don't know if helps.... Better to try...

**Comment by chivi** [comment]
I have the exact same issue. I've tried everything to get it working but it still won't get past that part. I have windows xp as my OS, and I have made sure that my bin folder is a variable path for my computer.... I don't understand what's wrong with it, considering that version 1.0 worked perfectly fine before

**Comment by Sqwurtski** [comment]
I instead did away with that psxpria tool all together and found a way to
get playstation games just as easy as getting a NES game. With a few extra
steps that takes 10-30 seconds.
On Tue, Jan 3, 2012 at 8:12 PM, chivi <
reply@reply.github.com

**Comment by tisaoil** [comment]
"I have the exact same issue. I've tried everything to get it working but it still won't get past that part. I have windows xp as my OS, and I have made sure that my bin folder is a variable path for my computer.... I don't understand what's wrong with it, considering that version 1.0 worked perfectly fine before"

To me it's happening with both versions, and I'm running on W7 ultimate 64..... So... Have no clue of the problem.....

**Comment by Sqwurtski** [comment]
I have W7 64-bit as well. Do you want to know a secret?

On Wed, Jan 4, 2012 at 7:03 AM, tisaoil <
reply@reply.github.com

**Comment by tisaoil** [comment]
You know what is the problem? And have the solution?!

**Comment by chivi** [comment]
Sqwurtski: let me guess, you used FPSE? lol, I actually want a solution for PSXperia

**Comment by tisaoil** [comment]
Well, I'm stil using FPSE... But I to whant a solution for PSXperia. Cause, why do I have to use some emulator softwere if my phone has already a native one!! I whant to be able to use it!! And for that I need someone to help me to understand what is happenig whith PSXperia, why doesn't whork????

**Comment by Sqwurtski** [comment]
haha, well I'm still concerned about PSXperia because its better than FPSE.
I just needed a brief moment of relaxation. I didn't have time to wait for
a solution so I found something else for the moment. My time is spent on
priorities now.

On Fri, Jan 6, 2012 at 9:13 AM, tisaoil <
reply@reply.github.com

**Comment by chivi** [comment]
I finally figured out the problem, being the no life that I am.
it turns out that our folder was missing a file called ps1_rom.bin in the data/ZPAK/data
now, through some research I did on Yifan Lu's thread, I learned that ps1_rom.bin is in fact the ps1 bios file....
so, in order to get the program working properly, you will need to legally rip your ps1 bios and place it in the data folder.

**Comment by tisaoil** [comment]
That.. doesn't make any sence to me.. Cause the files in data are taken from crash when you extract from mobile.
Soooo, I've tryed something. Take that rom file from original ZPAK folder, and place a copy in data/ZPAK/data, and psxperia started to work! But now, I don't know if it's slow or it just freezed in "creating temporary directory".
Let see how this goes! LoL!

**Comment by chivi** [comment]
yes, it works for me after I placed a rom file into the data.... but then after I install the program, it says that the data is corrupted....

as for my ZPAK file, there's no ps1_rom.bin file inside of mines

EDIT: I figured out my problem, hope you guys do too =]
